apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hwhkd1y9n-python
  janus-idp.io/tekton: hwhkd1y9n-python
  backstage.io/kubernetes-id: hwhkd1y9n-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hwhkd1y9n-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
